### ISSUE TITLE
Revert error - missing method named StartCopyFromBlob

### ISSUE THREAD

**Issue by holcakr** [bobalob/Azure-VM-Snapshots#2]
Hello,

First, thanks for your good work. 
Second, whenever I try to use function "Revert-AzureRMVMSnap" and choose snapshot, I get error (just after info "Reverting disk 0..."):

`Method invocation failed because [Microsoft.WindowsAzure.Storage.Blob.CloudPageBlob] does not contain a method named 'StartCopyFromBlob'.`

It originates from file AzureSnapFunctions.ps1:216 char:21

VM is already erased, but so far restore still waiting for finishing snapshot copy. I guess that after error it never happen so VM is lost. 
What can I do?

**Comment by holcakr** [comment]
Addendum: Method "StartCopyFromBlob" is deprecated. see https://stackoverflow.com/questions/39193026/azure-storage-copy-from-blob

**Comment by bobalob** [comment]
Interesting, thanks. What version of AzureRm Powershell module are you using please? You can get this with

    Get-Module AzureRm

As for the VM being lost: You can use storage explorer to manually work with snapshots of the VHD and the following is a script to make a new VM from an exisiting VHD:

https://gallery.technet.microsoft.com/Create-Azure-RM-VM-From-cab47980

**Comment by holcakr** [comment]
4.0.2
thx

**Comment by bobalob** [comment]
I've replaced the StartCopyFromBlob function with StartCopy and cleaned up a little.

I've also put in some error checking so that if the revert fails, it will put the VM back with the current disks so it's not quite as catastrophic!

Thanks for your input!

**Comment by holcakr** [comment]
Nice work thanks.
Its working...
