### ISSUE TITLE
Little issue in operation delete snapshot with force switch

### ISSUE THREAD

**Issue by holcakr** [bobalob/Azure-VM-Snapshots#3]
Hello,
When I run "Delete-AzureRMVMSnap" with "Force" switch, operation is done successfully. But one exception is thrown. Error text:
_You cannot call a method on a null-valued expression._
It shows on variable "SnapBlobs".
I believe it's because of in branch for "force" a code for setting a variable is missing (see line 148 in file "AzureSnapFunctions.ps1").  Specifically the text:
`$SnapBlobs = Get-AzureRmVmSnap -VMName $VMName -SnapshotGUID $Guid -GetBlobs`

**Comment by bobalob** [comment]
I can see the issue here and can reproduce.

This will have left snapshots of the VHD on your VM so you should clean them up by stopping the VM and using Azure Storage Explorer to delete them.

Investigating a fix now...

**Comment by bobalob** [comment]
Should hopefully be fixed now. Also added some additional error checking in the delete function.

Thanks again for your feedback.

**Comment by holcakr** [comment]
you are welcome. Thanks for your good work.
